version: "3.8"

services:
  bookstack-db:
    image: mariadb:10.6
    container_name: bookstack_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bookstack_db_data:/var/lib/mysql

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOST=bookstack-db
    volumes:
      - bookstack_app_data:/config
    ports:
      - "80:80"
    depends_on:
      - bookstack-db

volumes:
  bookstack_db_data:
  bookstack_app_data: